### ISSUE TITLE
Test for visual errors

### ISSUE THREAD

**Issue by thingscouldbeworse** [Robert8944/sqsg6#12]
With changes to CSS files and html edits may have left visual errors and CSS bugs in site pages. Button placement, text alignment, and other visual issues may exist in areas untested or when viewed on different devices with different screen sizes. 

To test, each page should be opened on standard desktop resolutions

 * 1280 x 768
 * 1920 x 1080
 * 3000 x 2000

and should be viewed in partials of these resolutions, manipulating window size until the container size reductions are triggered.

These pages should also be viewed on mobile devices with Firefox and Chrome mobile browsers. These viewport changes should be reflected in previous viewport settings, but mobile browsers may reveal other view errors triggered by HTML issues in these mobile browsers.

**Comment by thingscouldbeworse** [comment]
sign-in error text is off center and unstyled

**f ixed as of 6ffc56d5842dabd2d19e0fb1584caf4b9e4845f7

**Comment by ddilger** [comment]
Awesome. We can put this in the test plan document due April 3rd.

**Comment by thingscouldbeworse** [comment]
admin_user_info.php  has multiple errors

** Styling issues here are extensive, creating a separate issue for this page alone and marking it as a 'wontfix'

**Comment by thingscouldbeworse** [comment]
sign-in/register buttons on corresponding pages are aligned right for some reason

** fixed as of 6d5a65b6579cfe57b46968e201f1226bf785dad3

**Comment by thingscouldbeworse** [comment]
"Mailing Address" on *sign-up* should be properly styled
Radio buttons for genders should be horizontal

** fixed as of da0012a9d127cd6c789343519aa1e6123b4dba6b

**Comment by thingscouldbeworse** [comment]
Two columns on Profile page for desktop styling, can be left as is for mobile

Generally make better use of space for desktop styling

**Comment by thingscouldbeworse** [comment]
Un-center child elements on profile page, and sign-up (style like profile page)

**Comment by thingscouldbeworse** [comment]
All errors identified as a part of this issue are fixed as of d6b7c3852569d9a92545dd2b0138250d84951719 and many previous commits.
