### ISSUE TITLE
Name allows spaces

### ISSUE THREAD

**Issue by thingscouldbeworse** [Robert8944/sqsg6#18]
"Name allows spaces"

https://sites.google.com/site/group6sqs/project-updates/additionalrequirementsdeliveredbysqsonmarch1

**Comment by ddilger** [comment]
This can be done already since names are stored as a varchar. Alternatively this could be done by having separate first name and last name columns.

**Comment by thingscouldbeworse** [comment]
This was one of the issues that I added from the second set of requirements SQS gave us, at least a couple I guessed wouldn't need any additional work from us. 

I was pretty sure names already allowed spaces (because like you said, 'name' is just one field stored as a varchar) so if you're confident as well we can just close the issue
