### ISSUE TITLE
Account Groups

### ISSUE THREAD

**Issue by thingscouldbeworse** [Robert8944/sqsg6#20]
"Account Groups. (Group A, Group B)"

"Admin power to change other accounts group association. UserA -> Group A to UserA -> GroupB"

https://sites.google.com/site/group6sqs/project-updates/additionalrequirementsdeliveredbysqsonmarch1

**Comment by ddilger** [comment]
The admin can now add and remove users from groups. See http://dndi223.netlab.uky.edu/sqsg6/Training_site/admin_user_info.php

This admin page will need to be made better-looking in the future.
