### ISSUE TITLE
Sign-Up Options

### ISSUE THREAD

**Issue by thingscouldbeworse** [Robert8944/sqsg6#23]
"More information for creating an account. Such as: Name, email, gender, date of birth, address, home phone. "

https://sites.google.com/site/group6sqs/project-updates/additionalrequirementsdeliveredbysqsonmarch1

**Comment by ddilger** [comment]
Since time is running out I updated these on my version of the website. See

http://dndi223.netlab.uky.edu/sqsg6/Training_site/user_register.php
