### ISSUE TITLE
Replace "subscriber" table with "phone_list"

### ISSUE THREAD

**Issue by ddilger** [Robert8944/sqsg6#25]
Newly entered phone information must be associated with user accounts.

**Comment by thingscouldbeworse** [comment]
Make sure to change all the logic in index.php about registering numbers too, although it should just be changing the table referenced (unless you also changed the schema). It's possible to test and confirm the numbers being correctly added to the database, but texts aren't sending atm (see https://github.com/Robert8944/sqsg6/issues/13 )

**Comment by ddilger** [comment]
Now when you add a phone subscription it gets added to phone_list. The subscriber table is still updated as well. Instead of replacing the subscriber table, I just added the queries for phone_list into the file. Depending on how much time we have I may remove the subscriber table. Otherwise this issue has been completed.
