### ISSUE TITLE
Update how profiles are edited

### ISSUE THREAD

**Issue by ddilger** [Robert8944/sqsg6#35]
The new user data added (phone numbers, mail address) need editing options. 

Also, since profile information is now loaded from the features library, the way in which profiles are edited must change. Currently editing options are shown only if a "POST" variable says they should be. This "POST" variable needs to be replaced with a "SESSION" variable so that the variable can be seen from the features library.

**Comment by thingscouldbeworse** [comment]
The work on profiles is (as I understand it) all happening under here and Robert will close and update this issue as needed. We'll prune (#39) until then.

**Comment by thingscouldbeworse** [comment]
Fixed as of 9fdb1b01b5888e345f0e301a48459cd1e1f1c6c2 and subsequent cleaning commits from dumb mistakes.
