### ISSUE TITLE
Expand "Edit Profile" capabilities

### ISSUE THREAD

**Issue by ddilger** [Robert8944/sqsg6#39]
More details of user accounts have been added such as phone numbers, mail address, and group membership. These details can be seen on the profile page. Currently these cannot be edited. 

Note: Use of $_POST variables will no longer work, because group membership, phone number, and mailing address information is loaded from the features library (so that erroneous versions of these can be assigned to accounts). Use of $_SESSION variables may solve this problem.

**Comment by ddilger** [comment]
There is a difference between this and issue #35. The primary issue in #35 is allowing group updates, email updates, etc to work with the new SQL (and the use of SESSION instead of POST variables). 

This issue (#39) is lower priority.

The primary issue here is allowing new kinds of information to be displayed and updated, such as assigning primary phone number.

**Comment by thingscouldbeworse** [comment]
Pruning this issue to consolidate on #35.
