### ISSUE TITLE
Add new options to research screen

### ISSUE THREAD

**Issue by thingscouldbeworse** [Robert8944/sqsg6#4]
Combine login options from both websites, such as entering phone number on sign-up, address, role, etc.

**Comment by ddilger** [comment]
I am working on this a little on the profile page of the desktop version of the site:
http://dndi223.netlab.uky.edu/Training_site/profile.php

If someone else is working on it, please keep me up to date on which portions of this ticket you are working on.

**Comment by ddilger** [comment]
All that remains for this ticket is to display mailing address information (as far as I can tell). I will do this tomorrow morning.

**Comment by ddilger** [comment]
This information can now be seen on the profile page.
