### ISSUE TITLE
Remove vestigial code

### ISSUE THREAD

**Issue by thingscouldbeworse** [Robert8944/sqsg6#43]
There are some function calls, database executes, and other misc code that is left over from features we removed or over-wrote. There are also some helper files like 'docroottest.php' that need to be removed.

**Comment by ddilger** [comment]
I think this issue and issue #42 (Documentation of old code) are best done after we have a good set of regression tests to make sure we don't break anything.

**Comment by thingscouldbeworse** [comment]
Once we have tests ready any code we wrote needs to be gone through and pruned of unused code. Priority should be given to entire unused files over small snippets of code within functions.

First candidates;
docrotttest.php
Subscriber.sql
header_OLD.php

**Comment by thingscouldbeworse** [comment]
In addition to files already deleted through various commits, commit 5c59415eb686c919069e7e276cb6b107b209d61e seems to have gotten the last of it.
