### ISSUE TITLE
Regression tests

### ISSUE THREAD

**Issue by ddilger** [Robert8944/sqsg6#44]
Produce a document that lists what regression tests must be done after major changes to the code are written. It is best if this list is made before issues #42 and #43 are addressed.

**Comment by ddilger** [comment]
Most of the time when I make changes I just make sure that the data shown on profile.php and groups.php stays the same. I less frequently check the behavior of group updates on admin_user_info.php and account creation on user_registration.php.

**Comment by thingscouldbeworse** [comment]
This sort of happened but certainly isn't getting added to before the final deliverable. Closing.
