### ISSUE TITLE
Extensive testing of errors library

### ISSUE THREAD

**Issue by ddilger** [Robert8944/sqsg6#7]
Errors library off to a good start. Now I need to test it on more than just the menu bar feature.

**Comment by thingscouldbeworse** [comment]
Adding both Robert and Daniel  so whoever ends up writing errors and closing this issue has assigned people.

**Comment by ddilger** [comment]
There are now two nontrivial features in the errors library. Both of these features are related to phone subscription. One nontrivial error is the failure to notify the user whether he had successfully entered a new phone number. The other nontrivial error is the failure to list the phone numbers associated with the user.

(I say nontrivial because even though these are simply errors they were what SQS asked for.)

**Comment by ddilger** [comment]
Robert and I need to work alongside each other some time next week so that we can more productively introduce errors into the errors library.

**Comment by thingscouldbeworse** [comment]
Since we're not writing any new errors or error code, and are just documenting it, we may as well close out this issue regardless of its status.
